/**:
  ros__parameters:
    robotino_ip: 'localhost:8081' #'10.42.0.232' or 'localhost:8081'
    timeout: 1.0

    battery:
      update_rate: 1.0
      min_voltage: 22.0
      max_voltage: 24.5
      voltage_scale: 350.0
      critical_percentage: 0.15
      warning_percentage: 0.25

    sensors:
      update_rate: 10.0
      num_sensors: 9

    camera:
      width: 640
      height: 480
      fps: 10

    motors:
      max_linear_speed: 0.8
      max_angular_speed: 1.5
      max_acceleration: 0.5
      control_rate: 50.0

    odometry:
      update_rate: 20.0
      frame_id: "odom"
      child_frame_id: "base_link"
      covariance_linear: 0.1
      covariance_angular: 0.1

    navigation:
      max_linear_speed: 0.5
      max_angular_speed: 1.0
      position_tolerance: 0.1
      angular_tolerance: 0.1