/**:
  ros__parameters:
    serial_port: '/dev/ttyUSB0'
    frame_id: 'laser_frame'
    angle_compensate: true
    scan_mode: 'Standard'
    serial_baudrate: 115200
    angle_min: -3.14159
    angle_max: 3.14159
    range_min: 0.15
    range_max: 12.0
    publish_rate: 10.0
    inverted: true
